config/routes.rb
Rails.application.routes.draw do

  get "login/", to: "sessions#login", as: 'login'
  get "logout/", to: "sessions#logout"
  post "login_attempt/", to: "sessions#login_attempt"

  resources :users, only: [:new, :create, :show]

  resources :vacation_properties, path: "/properties"
  resources :reservations, only: [:index, :new, :create]
  post "reservations/incoming", to: 'reservations#accept_or_reject', as: 'incoming'

  post "reservations/connect_sms", to: 'reservations#connect_guest_to_host_sms'
  post "reservations/connect_voice", to: 'reservations#connect_guest_to_host_voice'

  # Home page
  root 'main#index', as: 'home'

end

app/models/vacation_property.rb
class VacationProperty < ActiveRecord::Base
  belongs_to :user # host
  has_many :reservations
  has_many :users, through: :reservations #guests
end

app/controllers/vacation_properties_controller.rb
class VacationPropertiesController < ApplicationController
  before_filter :authenticate_user, except: [:index]
  before_action :set_vacation_property_and_user, only: [:show, :edit, :update, :destroy]

  # GET /vacation_properties
  # GET /vacation_properties.json
  def index
    @vacation_properties = VacationProperty.all
  end

  # GET /vacation_properties/1
  # GET /vacation_properties/1.json
  def show
    @reservation = Reservation.new
    begin
      @current_reservation = Reservation.where(
        vacation_property_id: @vacation_property.id, 
        guest_phone: @user.phone_number,
        status: 1)
      .first 
    rescue Exception => e
      puts "e.message"
    end
  end

  # GET /vacation_properties/new
  def new
    @vacation_property = VacationProperty.new
  end

  # GET /vacation_properties/1/edit
  def edit
  end

  def create
    @user = current_user
    @vacation_property = @user.vacation_properties.create(vacation_property_params)

    respond_to do |format|
      if @vacation_property.save
        format.html { redirect_to @vacation_property, notice: 'Vacation property was successfully created.' }
        format.json { render :show, status: :created, location: @vacation_property }
      else
        format.html { render :new }
        format.json { render json: @vacation_property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vacation_property.update(vacation_property_params)
        format.html { redirect_to @vacation_property, notice: 'Vacation property was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation_property }
      else
        format.html { render :edit }
        format.json { render json: @vacation_property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vacation_property.destroy
    respond_to do |format|
      format.html { redirect_to vacation_properties_url, notice: 'Vacation property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation_property_and_user
      @user = current_user
      @vacation_property = VacationProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_property_params
      params.require(:vacation_property).permit(:description, :image_url)
    end
end

app/helpers/vacation_properties_helper.rb
module VacationPropertiesHelper
end

app/views/vacation_properties/_form.html.erb
<%= form_for(@vacation_property) do |f| %>
  <% if @vacation_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation_property.errors.count, "error") %> prohibited this vacation_property from being saved:</h2>

      <ul>
      <% @vacation_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Property', class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/vacation_properties/_reservation_form.html.erb
<%= form_for @reservation do |f| %>
  <div class="form-group">
  <%= f.label :message, "Would you like to say anything to the host?" %>
  <%= f.text_area :message, size: "10x10", class: "form-control", placeholder: "Hello! I am hoping to stay in your intergalactic suite..." %>
  </div>
  <div class="hidden">
  <%= f.text_field :name, value: @user.name %>
  </div>
  <div class="hidden">
  <%= f.text_field :guest_phone, value: @user.phone_number %>
  </div>
  <div class="hidden">
  <%= f.text_field :property_id, value: @vacation_property.id %>
  </div>
  <button class="btn btn-primary">Reserve Now</button>
<% end -%>

app/views/vacation_properties/edit.html.erb
<h1>Editing Vacation Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation_property %> |
<%= link_to 'Back', vacation_properties_path %>

app/views/vacation_properties/index.html.erb
<% content_for :hero do %>
  <div class="hero-text">
    <h1>Lodging fit for a captain</h1>
    <p>The Next Generation of vacation rentals.</p>
  </div>
<% end %>
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <% @vacation_properties.each do |vacation_property| %>
      <div class="col-md-4">
        <a href="/properties/<%= vacation_property.id %>" class="property">

          <img src="<%= vacation_property.image_url %>" />
          <h2><%= vacation_property.description %></h2>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/vacation_properties/new.html.erb
<% content_for :nav_bg do %>
  <!-- Nav Bar -->
  <nav class="navbar navbar-space">
  </nav>
<% end %>
<div class="container">
  <h1>New Vacation Property</h1>

  <%= render 'form' %>

  <%= link_to 'Back', vacation_properties_path %>
</div>

app/views/vacation_properties/show.html.erb
<% content_for :body_class, "property-page" %>
<p id="notice"><%= notice %></p>
<div class="property-detail">
  <div class="overview">
    <img src="<%= @vacation_property.image_url %>" />
  </div>
  <div class="container">
    <h1 ><%= @vacation_property.description %></h1><span><%= link_to 'Edit', edit_vacation_property_path(@vacation_property) %></span>
    <hr>
    <% if @current_reservation %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Your upcoming reservation details.</h3>
        </div>
        <div class="panel-body">
          <li><b>Status:</b> <%= @current_reservation.status %></li>
          <li><b>Host Name:</b> <%= @current_reservation.host.name %></li>
          
          <% if @current_reservation.phone_number %>
            <li><b>Contact Phone Number:</b> <a href="#"><%= @current_reservation.phone_number %></a></li>
          <% end %>
        </div>
      </div>
      <li><%= @current_reservation.message %></li>
    <% else %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Make a Reservation</h3>
        </div>
        <div class="panel-body">
          <%= render 'reservation_form' %>
        </div>
      </div>
    <% end %>
  </div>
</div>